include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    prefer_single_quotes: true
    directives_ordering: true
    avoid_redundant_argument_values: true
