export const AUDIT_ENTITY_TYPE = {
  ORDER: 'Order',
  PRODUCT: 'Product',
  CATEGORY: 'Category',
  DELIVERY_ZONE_FEE: 'DeliveryZoneFee',
  APP_SETTING: 'AppSetting',
  REVIEW: 'Review',
  REFUND: 'RefundRequest',
  SHIPPING_LABELS: 'ShippingLabels',
  ABANDONED_CART_SMS: 'AbandonedCartSms',
  PROMO: 'Promo',
  BANNER: 'Banner',
  LEGAL_PAGE: 'LegalPage',
} as const;
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPE)[keyof typeof AUDIT_ENTITY_TYPE];

export const AUDIT_ACTION = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  SOFT_DELETE: 'SOFT_DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  IMAGE_UPLOAD: 'IMAGE_UPLOAD',
  IMAGE_UPDATE: 'IMAGE_UPDATE',
  IMAGE_DELETE: 'IMAGE_DELETE',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',
  ZONE_FEE_UPDATE: 'ZONE_FEE_UPDATE',
  REVIEW_APPROVED: 'REVIEW_APPROVED',
  REVIEW_REJECTED: 'REVIEW_REJECTED',
  REVIEW_RESET_TO_PENDING: 'REVIEW_RESET_TO_PENDING',
  REFUND_APPROVED: 'REFUND_APPROVED',
  REFUND_REJECTED: 'REFUND_REJECTED',
  LABELS_PRINTED: 'LABELS_PRINTED',
  ABANDONED_CART_SMS_SENT: 'ABANDONED_CART_SMS_SENT',
  DELETE: 'DELETE',
  REORDER: 'REORDER',
} as const;
export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
